### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by Thendo-T** [losier/speed-test#1]
🙏🏾  could I please be a contributor to this

**Comment by losier** [comment]
Sure would love to work together @Thendo-T

**Comment by losier** [comment]
Hey @Thendo-T can you check getDownloadSpeed Hook and GetSpeed component i was trying to get download speed and it worked fine when i try to console.log but idk why it throws err when i try to render it

**Comment by Thendo-T** [comment]
import GetDownloadSpeed from "../hooks/getDownloadSpeed";

I think this import is the issue.

It should be:

import GetDownloadSpeed from "../hooks/GetDownloadSpeed";
