### ISSUE TITLE
Responsive CSS for Small and Medium Devices

### ISSUE THREAD

**Issue by losier** [losier/speed-test#3]
Need to fix the css for small and medium devices....

**Comment by Thendo-T** [comment]
this could be easily fixed if we use tailwindcss.

**Comment by losier** [comment]
I don't have much experience with tailwindcss

**Comment by itsOmSarraf** [comment]
Same here , I haven't started tailwind yet, sirf raw css ata hai .

**Comment by Thendo-T** [comment]
okay,let's do this. from now on we'll add comments on every file to help in understanding thought process and purpose of file, that way we get to learn from each other.
then I'll implement Tailwindcss with comments on every page having tailwind in it (which is almost all the components files and the pages/index.js file.

what do you think? @losier

**Comment by losier** [comment]
Sure sounds great to mee @Thendo-T tbh i never i don't know how to implement tailwind in nextjs btw are you on discord...

**Comment by Thendo-T** [comment]
cool. Yeah i do

**Comment by itsOmSarraf** [comment]
I won't be able to work on it before the 21st. Go ahead if someone has time.
